-- A Cleaner Clear — initial schema.
--
-- Access model: RLS is enabled on every table with NO policies, and all
-- privileges are revoked from the `anon` and `authenticated` roles. The only
-- way in is the service-role key, used server-side by Next.js route handlers.
-- The browser never talks to the database directly.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- submissions
-- ---------------------------------------------------------------------------
create table public.submissions (
  -- Generated by the client so retried uploads are idempotent.
  id                 uuid primary key,
  -- Short human code shown on the confirmation screen, e.g. "B47".
  -- No ambiguous characters (0/O, 1/I/L); generated server-side.
  code               text not null check (code ~ '^[A-HJKMNP-Z2-9]{3,6}$'),
  event_year         int  not null,
  -- Validated against config/event.ts in the API (not an FK: config lives in code).
  category_id        text not null check (category_id ~ '^[a-z0-9_-]{1,40}$'),
  photo_path         text not null,

  -- Contact info. Nullable only so scripts/purge-contacts.sql can wipe it;
  -- the constraints below require it until contacts_purged_at is set.
  name               text check (char_length(name) between 1 and 100),
  phone              text check (char_length(phone) between 7 and 30),
  team_name          text check (char_length(team_name) <= 100),
  note               text check (char_length(note) <= 140),
  -- Required by the API when the category has requiresWeight.
  weight_lbs         numeric(7, 2) check (weight_lbs > 0 and weight_lbs < 5000),

  lat                double precision check (lat between -90 and 90),
  lng                double precision check (lng between -180 and 180),
  zone               text check (char_length(zone) <= 10),

  is_minor           boolean not null default false,
  guardian_name      text check (char_length(guardian_name) between 1 and 100),
  guardian_phone     text check (char_length(guardian_phone) between 7 and 30),
  photo_consent      boolean not null default false,

  -- Random ID from the volunteer's localStorage: "my submissions" + rate limiting.
  device_id          text not null check (char_length(device_id) between 8 and 64),

  hidden             boolean not null default false,
  -- 1 = winner, 2/3 = runners-up (per category, per year; see unique index).
  winner_rank        int check (winner_rank between 1 and 3),

  created_at         timestamptz not null default now(),
  -- Set by POST /api/submissions/complete once the photo is in Storage.
  -- Rows with a null uploaded_at are pending and hidden from judges.
  uploaded_at        timestamptz,
  -- Set by scripts/purge-contacts.sql.
  contacts_purged_at timestamptz,

  constraint submissions_contact_required check (
    contacts_purged_at is not null or (name is not null and phone is not null)
  ),
  constraint submissions_guardian_required check (
    not is_minor
    or contacts_purged_at is not null
    or (guardian_name is not null and guardian_phone is not null)
  ),
  constraint submissions_location_pair check ((lat is null) = (lng is null))
);

comment on table public.submissions is
  'Contest entries. Contact columns must never be returned by public endpoints.';

-- Codes are unique within an event year (prize-tent lookup is by year + code).
create unique index submissions_year_code_key
  on public.submissions (event_year, code);

-- At most one winner / one 2nd / one 3rd per category per year.
create unique index submissions_winner_rank_key
  on public.submissions (event_year, category_id, winner_rank)
  where winner_rank is not null;

-- Judge feed: newest first within a category, uploaded rows only.
create index submissions_feed_idx
  on public.submissions (event_year, category_id, created_at desc)
  where uploaded_at is not null;

-- "My submissions" and per-device rate limiting.
create index submissions_device_idx
  on public.submissions (device_id, created_at desc);

-- ---------------------------------------------------------------------------
-- votes
-- ---------------------------------------------------------------------------
create table public.votes (
  id            uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.submissions (id) on delete cascade,
  judge_name    text not null check (char_length(judge_name) between 1 and 60),
  score         int  not null check (score between 1 and 5),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  -- Re-voting upserts on this key and updates the score.
  constraint votes_submission_judge_key unique (submission_id, judge_name)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger votes_set_updated_at
  before update on public.votes
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- hazards (P1) — logged alongside the sms: link to the safety lead
-- ---------------------------------------------------------------------------
create table public.hazards (
  id          uuid primary key default gen_random_uuid(),
  event_year  int not null,
  lat         double precision check (lat between -90 and 90),
  lng         double precision check (lng between -180 and 180),
  zone        text check (char_length(zone) <= 10),
  note        text check (char_length(note) <= 280),
  photo_path  text,
  device_id   text check (char_length(device_id) between 8 and 64),
  created_at  timestamptz not null default now()
);

create index hazards_year_created_idx
  on public.hazards (event_year, created_at desc);

-- ---------------------------------------------------------------------------
-- Lock it down: RLS on, no policies, no grants to client roles.
-- ---------------------------------------------------------------------------
alter table public.submissions enable row level security;
alter table public.votes       enable row level security;
alter table public.hazards     enable row level security;

alter table public.submissions force row level security;
alter table public.votes       force row level security;
alter table public.hazards     force row level security;

revoke all on public.submissions from anon, authenticated;
revoke all on public.votes       from anon, authenticated;
revoke all on public.hazards     from anon, authenticated;
revoke execute on function public.set_updated_at() from anon, authenticated, public;

-- ---------------------------------------------------------------------------
-- Storage: private `submissions` bucket.
--   * Uploads: browser PUTs to a signed upload URL from createSignedUploadUrl().
--   * Reads: server mints short-lived signed URLs for judges / the wall.
--   * No storage.objects policies are created, so anon/authenticated can't
--     list, read, or write objects directly.
-- Path convention: {event_year}/{submission_id}.jpg  (hazards: {event_year}/hazards/{id}.jpg)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'submissions',
  'submissions',
  false,
  5 * 1024 * 1024, -- 5 MB hard cap; client compresses to ~300–500 KB
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;
